/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package amazon.Forms;

import amazon.Forms.Main;
import static amazon.Forms.Main.ListRoute;
import static amazon.Forms.Main.ListStock;
import static amazon.Forms.Main.ListWarehouse;
import amazon.ListProduct;
import amazon.ListRoute;
import amazon.ListStock;
import amazon.ListWarehouse;
import amazon.Product;
import amazon.Route;
import amazon.Stock;
import amazon.Warehouse;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import amazon.SalesOrder;
import amazon.ListSalesOrder;
import amazon.NodoSalesOrder;
import amazon.Transaction;
import java.io.PrintWriter;

/**
 *
 * @author dariu
 */
public class Orders extends javax.swing.JFrame {

//    public ListWarehouse ListWarehouse = new ListWarehouse();
//    public ListProduct ListProduct = new ListProduct();
//    public ListStock ListStock = new ListStock();
//    public ListRoute ListRoute = new ListRoute();
      Main prueba = new Main();
      DefaultTableModel model = new DefaultTableModel();
        
    /**
     * Creates new form Orders
     */
    public Orders() {
        initComponents();
        this.setLocationRelativeTo(null);
        TableProducts.setModel(model);
        String title[] = {"Product Name", "Quantity", "Warehouse"};
        model.setColumnIdentifiers(title);
        TableProducts.getColumnModel();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableProducts = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        AddProduct = new javax.swing.JButton();
        f_StockWarehouse = new javax.swing.JComboBox<>();
        LabelProduct1 = new javax.swing.JLabel();
        f_StockProduct = new javax.swing.JComboBox<>();
        LabelWarehouse5 = new javax.swing.JLabel();
        f_Stock = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TableProducts);

        jLabel1.setText("Warehouse");

        jButton1.setText("Go Back to Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        AddProduct.setText("Add Product");
        AddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProductMouseClicked(evt);
            }
        });
        AddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductActionPerformed(evt);
            }
        });

        f_StockWarehouse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f_StockWarehouseFocusGained(evt);
            }
        });
        f_StockWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_StockWarehouseActionPerformed(evt);
            }
        });

        LabelProduct1.setText("Product:");

        f_StockProduct.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f_StockProductFocusGained(evt);
            }
        });
        f_StockProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_StockProductActionPerformed(evt);
            }
        });

        LabelWarehouse5.setText("Stock:");

        f_Stock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                f_StockFocusLost(evt);
            }
        });

        jButton2.setText("Delete Product");

        jButton3.setText("Make an Order");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelProduct1)
                            .addComponent(LabelWarehouse5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(f_StockProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f_StockWarehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddProduct, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(f_StockWarehouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelProduct1)
                    .addComponent(f_StockProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelWarehouse5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProductMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AddProductMouseClicked

    private void AddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductActionPerformed
        ListSalesOrder newOrder = new ListSalesOrder();
        SalesOrder obj_order = new SalesOrder();
        String rowData[] = new String[25];
        int cont = 0;
        try{
            rowData[0] = f_StockWarehouse.getSelectedItem().toString();
        rowData[1] = f_StockProduct.getSelectedItem().toString();
        rowData[2] = f_Stock.getText();
        
        for (int x = 0; x <= prueba.ListProduct.getLenght() - 1; x++) {
            obj_order .setNameProduct(prueba.ListProduct.getProduct(x).getName());
        }
        
        obj_order .setNameProduct(rowData[0]);
        obj_order.setOrderNumber(cont+1);
        obj_order.setAmount(Integer.parseInt(rowData[2]));
        obj_order.setWarehouse(rowData[0]);
        
            
        newOrder.insertEnd(obj_order);
        model.addRow(rowData);
        JOptionPane.showMessageDialog(null, "Producto añadido a la lista!");
        } catch (Exception e) {
            
        }
        
        
    }//GEN-LAST:event_AddProductActionPerformed

    private void f_StockWarehouseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_StockWarehouseFocusGained
        // TODO add your handling code here:
        f_StockWarehouse.removeAllItems();
        for (int i = 0; i <= prueba.ListWarehouse.getLenght() - 1; i++) {
            f_StockWarehouse.addItem(prueba.ListWarehouse.getWarehouse(i).getCode());
        }
    }//GEN-LAST:event_f_StockWarehouseFocusGained

    private void f_StockWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_StockWarehouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_StockWarehouseActionPerformed

    private void f_StockProductFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_StockProductFocusGained
        // TODO add your handling code here:
        f_StockProduct.removeAllItems();
        for (int x = 0; x <= prueba.ListProduct.getLenght() - 1; x++) {
            f_StockProduct.addItem(prueba.ListProduct.getProduct(x).getName());
        }
    }//GEN-LAST:event_f_StockProductFocusGained

    private void f_StockProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_StockProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_StockProductActionPerformed

    private void f_StockFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_StockFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_f_StockFocusLost

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String directoryName = System.getProperty("user.dir");

        try ( PrintWriter writer = new PrintWriter(directoryName + "/Data/amazon_factura.txt", "UTF-8")) {
            writer.println("Almacenes;");
            for (int i = 0; i <= ListWarehouse.getLenght() - 1; i++) {
                writer.println(ListWarehouse.getWarehouse(i).getName());
                //imprimir productos del almacen
                
                for (int x = 0; x <= ListStock.getLenght() - 1; x++) {
                    if (ListStock.getStock(x).getWarehouse().equals(ListWarehouse.getWarehouse(i).getCode())) {
                        if (x < ListStock.getLenght() - 1) {
                            writer.println(ListStock.getStock(x).getName() + "," + ListStock.getStock(x).getAmount());
                        } else {
                            writer.println(ListStock.getStock(x).getName() + "," + ListStock.getStock(x).getAmount() + ";");
                        }
                    }
                }

            }

            writer.println("Rutas;");
            for (int i = 0; i <= ListRoute.getLenght() - 1; i++) {
                writer.println(ListRoute.getRoute(i).getWarehouse() + "," + ListRoute.getRoute(i).getWarehouseAdjacent() + "," + ListRoute.getRoute(i).getWeight());
            }
            writer.close();
            JOptionPane.showMessageDialog(null, "El repositorio ha sido salvado en " + directoryName + "/Data/amazon.txt");
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orders().setVisible(true);
            }
        });
    }


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProduct;
    private javax.swing.JLabel LabelProduct1;
    private javax.swing.JLabel LabelWarehouse5;
    private javax.swing.JTable TableProducts;
    private javax.swing.JTextField f_Stock;
    private javax.swing.JComboBox<String> f_StockProduct;
    private javax.swing.JComboBox<String> f_StockWarehouse;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
